services:
  - type: web
    name: victoria-online
    env: node
    runtime: node # Explicitly specify Node.js runtime
    repo: https://github.com/bbaxter361/Vicki-Online.git
    region: oregon
    branch: main
    plan: free
    buildCommand: npm install # Ensure Node.js build command
    startCommand: node replaybrick-dashboard-server.cjs
    autoDeploy: true
    healthCheckPath: /
